export const NAME = '@APP'

export const SCREEN_DIALOG_FORM_NAME = 'SCREEN_DIALOG'
export const TAB_DIALOG_FORM_NAME = 'TAB_DIALOG'

export const USER_AGENT_DIALOG_FORM_NAME = 'USER_AGENT_FORM_DIALOG'
